language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: DJUR/YEdjaJxglOWHK2JBbogRuJroZVQypRgw+ZeFO7uudccoCtLKtFgcvferZI7FKj/c7muXf+sXaIgUVjTYZMeWuacgjF3jtZei8oqi5Pv2wWMMUyfmcYurGKR4p3QSxCY8WPR0+vgESg9sarxZeOlMIqM6mimCry53bwWjpkx6w4v31uYIBESIRHnrDe9kp0L3uD1yR9DUV0CmGJKQ1b6rfh/KDfraRgbrtV7JCE/WTGZpeYQo2kb+gn+xz0tGnCq0QCHTTwEt97satI1Z6Q2KFNDnLjq9qL/WeMq4l4XUVyHY7ztOHdLZfBG0fDCXABwo291Zsqgc3CHDH7B76yhff8Oyj0FsnbbwZcxYSP8vPf/MCGD5cnLYWShvGZvXVwTQjgUrtNqXO59hRFs9YRdAA5r4hc9a6+jvzch0Vvg87FGgX0SjsTFF14z9lcueM2MlHjTn7fJD/wO9FO47jianMMrYVGwKP7KzD5Ivwx+TA5VOT4qhr1LvuatyFrHRaYgLpDNE51jTVpZ2kY/bnQkMPdYNkoPUVVO2zFv6IJ5aJ371K5n+w38zx8hg2PwhqJCYmK4T7WDsO7jCPKVhZh1TlXRReZTCKM4F1GV1Lpdbnug6HlXyh3VGzVQq11KHqiS1hk8ak2a/Et/Uvrax6YPyheMYQ4UPpy8WJJiw1E=
  file:
    - 'css-declarations.js'
    - 'css-declarations.min.js'
  on:
    tags: true
