language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Vnc6MSsxJkuZB6Y6L1xeNSUM3Q4iQGUpAv7Z3O80kmXTYl58loqK/5kQhwa+62oTobKDDGBLeu/vTRa3kcTQoAzmMhAQrASTAOcyHyhEpA1MU6FcPcgwiXD1oRUnmlJeUYG7wU80TRBKo1catucm19NcxYOePcNB5djzu4QUAfp4NObdkMT4/JrNE0L4YtaiD3Eg3Fi598dweFueIg1fmxdBNRujNssrhLROscnl7RwFqO3qZ50iR73spLiXosjLa+nUsSxO/fxpVHdsn4j+nIsbd6EbqJBtfNdJ8TYDvaLdrXdSvOyNyOmVN3oCmCbQiO5XCNP9FSTHsvw+BHinLWdJSVG+Pc7oJ2w8SSkq3ksef0/ORRpOgHm4xy4/4HutNYidBgXq0l7qxwXfaa3yITxnGRQb/pH3LJpNhiLveRnZUCmC21L8Ydf/oatq7Ulyd0jzS88IAVEQACYY/6RManDYQUcCRtHAYELvrym9RxptnE4kGvBvZn5rYuQ+1ObgGiq3TRf6WkOnwv7oMUMYpYQTVew7+ZWsL6BVTpyTaQhEOgLf/FbeXJG5MAZeV1KYxq/rlzgeRNdbjMkKrDm0fbFHnmE1E3lsT1BhoIyCX29Cy7l3AB4mjmTjQsPzanq3t3ubHofJAPMbYwbDnCFlyVKaNDwoGBBle86DhaU7eWQ=
  file:
    - "css-declarations.js"
    - "css-declarations.min.js"
  on:
    tags: true
