language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: MEXy1Zs+XtALW0Mh1T3AenBHIoP7DeUt9IacEp5GbCC+LSCy9w/zftSonInHPb9O/ITLrZbLVJthG8UjLXfaGmvbLmQDtKw1gzNlBLc9JvVxGl55S3EADqeD54eK1cGkAOJ8Lx6s3V3Rt5rPO+0YZpkxPbx8aQ7As42LSrEGI6L0WS3iVUNaC6l/1vOohrSo+SCt0iBnU7W5CEuX3Cn3yTSOCHw5VTqm2i0mQNw6WbdVdO74qqXewbQopyb1QYwIySf517Sgwa9zcRo3Q48MkqlgCo2+lMksuUER0YE2S+O6pGzUN/oD3P5YqWTnVV6FpzZmjO/QkDl7JCCzpDOaBMuDWDKWdE0TtqsTXb6/RlVeDby63ET7plWpiBTQ3sijCluggg7Am8rvEY50gAoYq38TvF53xS9TRB7hf5fyhxHLF/sz9OLAZVPoFea0cRJyxmOguhFcTrjOXXZXm8Ee10oDNrZby5j5y3GhF9z758naV+fcOQHNjG+jjqkOgKidPSE+6nCpja571faTTEghhey0PW3igcLu+OC5Q5lt+Y5v3MWkZ3SMPy5wmQuBa0TbbChqKrZEKCmuU127sQ/ex6sJtu5SFSCvLOK11fhnnqfOFLCxAipn3zs0MsNbiKw1/JNM95VzJKlrTIVIlRM2Att8VcLbWOfaCkQDi2lv2Ok=
  file:
    - "css-declarations.js"
    - "css-declarations.min.js"
  on:
    tags: true
